### ISSUE TITLE
ontresearch/epi2melabs-notebook medaka_consensus & bcftools dependency error

### ISSUE THREAD

**Issue by rjwswenson** [epi2me-labs/nanolabs#1]
Hello, 

In trying to run **bcftools -v** the following error occurs:

```bcftools: error while loading shared libraries: libgsl.so.25: cannot open shared object file: No such file or directory```

This also causes medaka_consensus to not run properly, throwing the same error.  What LD_LIBRARY_PATH target lib location contains the libgsl.so.25 library dependency, or how do we resolve this issue?  We prefer to employ medaka_consensus instead of going back to a different polishing consensus sequence strategy such as employing racon, canu, and pilon.

Thanks.
Ryan

**Comment by cjw85** [comment]
Duplicates https://github.com/nanoporetech/medaka/issues/363
